import web3 from "./web3";

const address = "0x0F5dE9CB834c7cd88bB0C32189288400Ed78DD8b";
const abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
    signature: "constructor",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "CooperativeStores",
    outputs: [
      { internalType: "string", name: "StoreName", type: "string" },
      { internalType: "address", name: "StoreAddress", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x93fc66cf",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "Post_Project",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xfe767687",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "Remove_Project",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x635c987f",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "Send_Money_Beneficiary",
    outputs: [],
    stateMutability: "payable",
    type: "function",
    payable: true,
    signature: "0xa6e0b44d",
  },
  {
    inputs: [
      { internalType: "string", name: "_productId", type: "string" },
      { internalType: "string", name: "_productName", type: "string" },
      { internalType: "uint256", name: "_price", type: "uint256" },
    ],
    name: "addProduct",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xf28ea1c1",
  },
  {
    inputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "string", name: "product_name", type: "string" },
      { internalType: "uint256", name: "price", type: "uint256" },
    ],
    name: "add_product",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x100b593d",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "allProducts",
    outputs: [
      { internalType: "string", name: "productId", type: "string" },
      { internalType: "string", name: "productName", type: "string" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "bool", name: "ongoing", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xcfaaef56",
  },
  {
    inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
    name: "approveRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0xd7d1bbdb",
  },
  {
    inputs: [],
    name: "approversCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x82fde093",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "beneficiaries",
    outputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "description", type: "string" },
      { internalType: "uint256", name: "maxContr", type: "uint256" },
      { internalType: "uint256", name: "collectedAmount", type: "uint256" },
      { internalType: "address payable", name: "store", type: "address" },
      { internalType: "bool", name: "complete", type: "bool" },
      { internalType: "uint256", name: "approvalCount", type: "uint256" },
      { internalType: "bool", name: "approved", type: "bool" },
      { internalType: "bool", name: "display", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xefeb5e58",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "charityOrgs",
    outputs: [
      { internalType: "string", name: "OrgName", type: "string" },
      { internalType: "address payable", name: "OrgAddress", type: "address" },
      { internalType: "string", name: "OrgDescription", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x378405e4",
  },
  {
    inputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "description", type: "string" },
      { internalType: "uint256", name: "maxContr", type: "uint256" },
    ],
    name: "createRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x23fe79b8",
  },
  {
    inputs: [
      { internalType: "string", name: "_donatorName", type: "string" },
      { internalType: "string", name: "_donatorMessage", type: "string" },
    ],
    name: "create_donator",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x7e86a148",
  },
  {
    inputs: [],
    name: "donateVote",
    outputs: [],
    stateMutability: "payable",
    type: "function",
    payable: true,
    signature: "0xd41c8922",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "donators",
    outputs: [
      { internalType: "string", name: "donatorName", type: "string" },
      { internalType: "string", name: "donatorMessage", type: "string" },
      { internalType: "uint256", name: "amountDonated", type: "uint256" },
      { internalType: "uint256", name: "donationValue", type: "uint256" },
      { internalType: "address", name: "donatorAddress", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xac62f566",
  },
  {
    inputs: [],
    name: "getAllProducts",
    outputs: [
      {
        components: [
          { internalType: "string", name: "productId", type: "string" },
          { internalType: "string", name: "productName", type: "string" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "bool", name: "ongoing", type: "bool" },
        ],
        internalType: "struct CharitySystem.Product[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x02ee3a52",
  },
  {
    inputs: [],
    name: "getBeneficiaries",
    outputs: [
      {
        components: [
          { internalType: "string", name: "title", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "uint256", name: "maxContr", type: "uint256" },
          { internalType: "uint256", name: "collectedAmount", type: "uint256" },
          { internalType: "address payable", name: "store", type: "address" },
          { internalType: "bool", name: "complete", type: "bool" },
          { internalType: "uint256", name: "approvalCount", type: "uint256" },
          { internalType: "bool", name: "approved", type: "bool" },
          { internalType: "bool", name: "display", type: "bool" },
        ],
        internalType: "struct CharitySystem.Beneficiary[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x913b722c",
  },
  {
    inputs: [],
    name: "getCharityOrgs",
    outputs: [
      {
        components: [
          { internalType: "string", name: "OrgName", type: "string" },
          {
            internalType: "address payable",
            name: "OrgAddress",
            type: "address",
          },
          { internalType: "string", name: "OrgDescription", type: "string" },
        ],
        internalType: "struct CharitySystem.CharityOrg[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xb8c2003b",
  },
  {
    inputs: [],
    name: "getCoOpStores",
    outputs: [
      {
        components: [
          { internalType: "string", name: "StoreName", type: "string" },
          { internalType: "address", name: "StoreAddress", type: "address" },
        ],
        internalType: "struct CharitySystem.CoopStore[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x4baab5ed",
  },
  {
    inputs: [],
    name: "getDonators",
    outputs: [
      {
        components: [
          { internalType: "string", name: "donatorName", type: "string" },
          { internalType: "string", name: "donatorMessage", type: "string" },
          { internalType: "uint256", name: "amountDonated", type: "uint256" },
          { internalType: "uint256", name: "donationValue", type: "uint256" },
          { internalType: "address", name: "donatorAddress", type: "address" },
        ],
        internalType: "struct CharitySystem.Donator[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xbf1482fa",
  },
  {
    inputs: [],
    name: "getPayments",
    outputs: [
      {
        components: [
          { internalType: "string", name: "description", type: "string" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "string", name: "sender", type: "string" },
          { internalType: "string", name: "receiver", type: "string" },
          { internalType: "bool", name: "completed", type: "bool" },
        ],
        internalType: "struct CharitySystem.Payment[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xd56bd142",
  },
  {
    inputs: [],
    name: "getProducts",
    outputs: [
      {
        components: [
          { internalType: "string", name: "productId", type: "string" },
          { internalType: "string", name: "productName", type: "string" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "bool", name: "ongoing", type: "bool" },
        ],
        internalType: "struct CharitySystem.Product[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xc29b2f20",
  },
  {
    inputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "make_donations",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x218d2f13",
  },
  {
    inputs: [],
    name: "manager",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x481c6a75",
  },
  {
    inputs: [],
    name: "minContr",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0xb8b142de",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "payments",
    outputs: [
      { internalType: "string", name: "description", type: "string" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "string", name: "sender", type: "string" },
      { internalType: "string", name: "receiver", type: "string" },
      { internalType: "bool", name: "completed", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
    constant: true,
    signature: "0x87d81789",
  },
  {
    inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
    name: "transferToStore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
    signature: "0x170f62b6",
  },
];

export default new web3.eth.Contract(abi, address);
